In [28]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [29]:
df=sns.load_dataset('titanic')

# 1. Logistic Regression

In [30]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [31]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [32]:
df.info() #deck have many null values 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [33]:
df_drop=df.drop([ 'class', 'who', 'adult_male', 'deck', 'embark_town','alive'],axis=1)

In [34]:
df_drop

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0           0       3    male  22.0      1      0   7.2500        S  False
1           1       1  female  38.0      1      0  71.2833        C  False
2           1       3  female  26.0      0      0   7.9250        S   True
3           1       1  female  35.0      1      0  53.1000        S  False
4           0       3    male  35.0      0      0   8.0500        S   True
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
886         0       2    male  27.0      0      0  13.0000        S   True
887         1       1  female  19.0      0      0  30.0000        S   True
888         0       3  female   NaN      1      2  23.4500        S  False
889         1       1    male  26.0      0      0  30.0000        C   True
890         0       3    male  32.0      0      0   7.7500        Q   True

[891 rows x 9 columns]

In [35]:
df_drop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [36]:
df_drop['age'].fillna(df['age'].mean(),inplace=True)

In [37]:
df_drop.dropna(subset=['embarked'],inplace=True)

In [38]:
df_drop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


### Label encode

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
le=LabelEncoder()

In [41]:
df_drop.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [42]:
df_drop['sex'] = le.fit_transform(df_drop['sex'])
df_drop['embarked'] = le.fit_transform(df_drop['embarked']) #S=2, C=0, Q=1

In [43]:
df_drop.head()

survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [44]:
final_df=df_drop

In [45]:
final_df['age']=final_df['age'].astype(int)

In [46]:
final_df

survived  pclass  sex  age  sibsp  parch     fare  embarked  alone
0           0       3    1   22      1      0   7.2500         2  False
1           1       1    0   38      1      0  71.2833         0  False
2           1       3    0   26      0      0   7.9250         2   True
3           1       1    0   35      1      0  53.1000         2  False
4           0       3    1   35      0      0   8.0500         2   True
..        ...     ...  ...  ...    ...    ...      ...       ...    ...
886         0       2    1   27      0      0  13.0000         2   True
887         1       1    0   19      0      0  30.0000         2   True
888         0       3    0   29      1      2  23.4500         2  False
889         1       1    1   26      0      0  30.0000         0   True
890         0       3    1   32      0      0   7.7500         1   True

[889 rows x 9 columns]

### Train test Split 

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X=final_df.drop(['survived'],axis=1)
y=final_df['survived']

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [51]:
from sklearn.linear_model import LogisticRegression
model =LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [52]:
y_pred=model.predict(X_test)

In [53]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [54]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

#### Logistric Regression >> Classification Problem (Use Confusion Matrix for Evaluation)

In [55]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [56]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [57]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]], dtype=int64)

In [58]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



# 2. KNN Classifier 
* Depend on distance so we have to do feature scaling 

In [59]:
final_df.head()

survived  pclass  sex  age  sibsp  parch     fare  embarked  alone
0         0       3    1   22      1      0   7.2500         2  False
1         1       1    0   38      1      0  71.2833         0  False
2         1       3    0   26      0      0   7.9250         2   True
3         1       1    0   35      1      0  53.1000         2  False
4         0       3    1   35      0      0   8.0500         2   True

In [70]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [71]:
# direct sab ko hi standard sacle kardo 

X_train_scaled=scaler.fit_transform(X_train)
X_train_scaled


array([[-1.58410418, -1.40530972, -0.58667407, ...,  2.43059683,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.35813533,
        -1.95246446, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.49094895,
         0.58770431,  0.81076671],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.12471679,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.66286134, ...,  0.04708333,
         0.58770431, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.47611594,
         0.58770431,  0.81076671]])

In [72]:
X_test_scaled=scaler.fit_transform(X_test)
X_test_scaled

array([[ 0.87837838,  0.83380939, -0.05614186, ..., -0.47215047,
         0.5836712 ,  0.82416338],
       [-1.52702703, -1.19931487, -1.19358508, ...,  1.69902381,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487, -1.19358508, ..., -0.40656752,
        -1.88998295, -1.21335165],
       ...,
       [ 0.87837838, -1.19931487,  0.75631758, ..., -0.01653915,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487,  0.35008786, ..., -0.31734953,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487, -2.00604452, ..., -0.30089329,
         0.5836712 , -1.21335165]])

In [73]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)

In [74]:
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [75]:
y_pred_knn=knn_model.predict(X_test_scaled)

In [76]:
y_pred_knn

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [77]:
accuracy_score(y_test,y_pred_knn)

0.7921348314606742

In [78]:
confusion_matrix(y_test,y_pred_knn)

array([[89, 20],
       [17, 52]], dtype=int64)

In [79]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178



# 3. Naive Bayes

In [80]:
X_test.head()

pclass  sex  age  sibsp  parch      fare  embarked  alone
281       3    1   28      0      0    7.8542         2   True
435       1    0   14      1      2  120.0000         2  False
39        3    0   14      1      0   11.2417         0  False
418       2    1   30      0      0   13.0000         2   True
585       1    0   18      0      2   79.6500         2  False

In [81]:
from sklearn.naive_bayes import GaussianNB

In [82]:
NB_model = GaussianNB()

In [83]:
NB_model.fit(X_train,y_train)

GaussianNB()

In [84]:
y_NB_pred=NB_model.predict(X_test)

In [85]:
y_NB_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [86]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [87]:
accuracy_score(y_test,y_NB_pred)

0.7752808988764045

In [88]:
confusion_matrix(y_test,y_NB_pred)

array([[84, 25],
       [15, 54]], dtype=int64)

In [89]:
print(classification_report(y_test,y_NB_pred))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



# 4. Decision Tree >> Scaling Karni padegi

In [90]:
from sklearn.tree import DecisionTreeClassifier

In [91]:
DT_model=DecisionTreeClassifier()

In [92]:
DT_model.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [93]:
y_DT_pred=DT_model.predict(X_test_scaled)

In [94]:
y_DT_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1], dtype=int64)

In [95]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [96]:
accuracy_score(y_test,y_DT_pred)

0.6853932584269663

In [97]:
confusion_matrix(y_test,y_DT_pred)

array([[76, 33],
       [23, 46]], dtype=int64)

In [98]:
print(classification_report(y_test,y_DT_pred))

              precision    recall  f1-score   support

           0       0.77      0.70      0.73       109
           1       0.58      0.67      0.62        69

    accuracy                           0.69       178
   macro avg       0.67      0.68      0.68       178
weighted avg       0.70      0.69      0.69       178



# 5. Support Vector Machine (SVM)  >> Feature scaling needed 

In [99]:
from sklearn.svm import SVC

In [100]:
svm_model=SVC(kernel='rbf')    #rfb default kernel hota hai (we can use multiple models)

In [101]:
svm_model.fit(X_train_scaled,y_train)

SVC()

In [102]:
y_svm_pred=svm_model.predict(X_test_scaled)

In [103]:
y_svm_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [104]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [108]:
accuracy_score(y_test,y_svm_pred)

0.8258426966292135

In [109]:
confusion_matrix(y_test,y_svm_pred)

array([[96, 13],
       [18, 51]], dtype=int64)

In [110]:
print(classification_report(y_test,y_svm_pred))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178



# Till Now  SVM is best model to predict the Survival 

# Now Lets see what Cross Validation Can do 

In [111]:
final_df.head()

survived  pclass  sex  age  sibsp  parch     fare  embarked  alone
0         0       3    1   22      1      0   7.2500         2  False
1         1       1    0   38      1      0  71.2833         0  False
2         1       3    0   26      0      0   7.9250         2   True
3         1       1    0   35      1      0  53.1000         2  False
4         0       3    1   35      0      0   8.0500         2   True

In [112]:
X=final_df.drop(['survived'],axis=1)
y=final_df['survived']

In [113]:
from sklearn.model_selection import cross_val_score

In [114]:
scaler=StandardScaler()
X_scaled = scaler.fit_transform(X)

In [115]:
scores=cross_val_score(svm_model,X_scaled,y,cv=5,scoring='accuracy')

In [116]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]


In [118]:
Average_accuracy_svm=scores.mean()
Average_accuracy_svm

0.8279375357074844

In [88]:
scores1=cross_val_score(knn_model,X_scaled,y,cv=5,scoring='accuracy')

In [89]:
scores1.mean()

0.7986542245921411

In [121]:
scores2=cross_val_score(model,X_scaled,y,cv=5,scoring='accuracy')


In [123]:
scores2.mean()

0.7919380435472609

In [126]:
scores3=cross_val_score(NB_model,X_scaled,y,cv=5,scoring='accuracy')
scores3.mean()

0.7840474830191074

In [128]:
scores4=cross_val_score(DT_model,X_scaled,y,cv=5,scoring='accuracy')
scores4.mean()

0.7818066400050784

# Hyperparameter Tuning 

## Grid Search CV